### ISSUE TITLE
[PM : Error console] Preference parsing warning

### ISSUE THREAD

**Issue by biopsin** [0strodamus/CleanLinks2#1]
Heya, 
forgot about this; but to silence the warnings on start.
@ https://forum.palemoon.org/viewtopic.php?f=46&t=25356#p203017

replace in prefs.js; all single backslashes with double backslashes in lines 2,3 and 7

**Comment by 0strodamus** [comment]
Sorry, but that isn't going to be implemented. Sure, it will silence the warnings. However, it will also break the regular expressions. A \\\ in regex represents a single literal \ character (see [Metacharacters Inside Character Classes](http://www.regular-expressions.info/charclass.html)). For example, instead of \w matching one letter, underscore, or digit, \\w will match one backslash followed by a w character.

I did spend a lot of time when I first created this fork trying to silence these warnings and I don't see the value in spending any more of my time on it. I also do not consider them indicative of an issue with the extension.
